export const meetings = [
    //MONDAY
    {
        id: 1,
        visible: true,
        day: 'Monday',
        timePT: '7:00 AM PT',
        title: 'Living Sober Sunrise Mtg: Reading from “Living Sober”',
        type: 'AA',
        format: 'Unknown',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://zoom.us/j/91608348235?pwd=ZVg4bEt2dWh2THI1WDBwY3AwQW1IUT09',
        zoomID: '916 0834 8235',
        zoomPW: 'sunrise',
        contactName: 'Crystal'
    },
    {
        id: 2,
        visible: true,
        day: 'Monday',
        timePT: '8:15 AM PT',
        title: 'Hope For Today (Al Anon-ACA Focus)',
        type: 'ACA',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serentity Room',
        zoom: 'https://us02web.zoom.us/j/87887397285',
        zoomID: '878 8739 7285',
        zoomPW: '314887',
        contactName: ''
    },
    {
        id: 3,
        visible: true,
        day: 'Monday',
        timePT: '9:00 AM PT',
        title: 'The Stepper! A fun step study.',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Erik C.'
    },
    {
        id: 4,
        visible: true,
        day: 'Monday',
        timePT: '11:00 AM PT',
        title: 'Gettin’ Lit: Weekly Book Study, Big Book Mondays, 12 Steps, and 12 Traditions.',
        type: 'AA',
        format: 'Unknown',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/82633330760?pwd=alpvUUdlbXhpaUZydWs5Z1Q0Zjlqdz09',
        zoomID: '283 595 3698',
        zoomPW: 'Literature',
        contactName: 'Melissa H.'
    },
    {
        id: 5,
        visible: true,
        day: 'Monday',
        timePT: '12:00 PM PT',
        title: 'Parental Guidance: A meeting for sober parents in AA',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/89389919893?pwd=Y09FMWRMU1ZFbzZSL2ZFRUJBdTV6Zz09',
        zoomID: '893 8991 9893',
        zoomPW: 'AAvillage',
        contactName: 'Lauren'
    },
    {
        id: 6,
        visible: true,
        day: 'Monday',
        timePT: '1:30 PM PT',
        title: 'Zaddies & Addies: A safe space for LGBTQIA2S+ and allies to recover',
        type: 'AA',
        format: 'Literature/Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/3893357431?pwd=ZnlYTm44QS9HVmxBTjJUZlRvb1Jydz09',
        zoomID: '389 335 7431',
        zoomPW: 'Sober2021',
        contactName: 'Unknown'
    },
    {
        id: 7,
        visible: true,
        day: 'Monday',
        timePT: '3:00 PM PT',
        title: 'House of Cards: AA meeting focusing on the family dynamic in recovery',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/83585017311?pwd=eXJta3Q2eW9aTWwzZ3JaQlRiZ0NYUT09',
        zoomID: '835 8501 7311',
        zoomPW: '4343',
        contactName: 'Alyssa L.'
    },
    {
        id: 8,
        visible: true,
        day: 'Monday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Justin R.'
    },
    {
        id: 9,
        visible: true,
        day: 'Monday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'N/A'
    },
    {
        id: 10,
        visible: true,
        day: 'Monday',
        timePT: '7:00 PM PT',
        title: 'Double Trouble: A Safe Space to Discuss Dual Diagnosis',
        type: 'Dual Diagnoses',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/5013772720',
        zoomID: '501 377 2720',
        zoomPW: 'recovery',
        contactName: 'Unknown'
    },
    {
        id: 11,
        visible: true,
        day: 'Monday',
        timePT: '7:30 PM PT',
        title: 'Young Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Gabe'
    },
    {
        id: 12,
        visible: true,
        day: 'Monday',
        timePT: '8:00 PM PT',
        title: 'Humble Pride at Radford: LGBTQ AND SUPPORTERS!',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us04web.zoom.us/j/9072328568?pwd=bm5xZzdNOVE3ZEhKMHYwanVnVVl1dz09',
        zoomID: '907 232 8568',
        zoomPW: 'RPride',
        contactName: 'Gio'
    },
    {
        id: 13,
        visible: true,
        day: 'Monday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Ash'
    },

    //TUESDAY
    {
        id: 14,
        visible: true,
        day: 'Tuesday',
        timePT: '7:00 AM PT',
        title: 'First Things First: 12 x 12 Book Study',
        type: 'AA',
        format: 'Book Study',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us06web.zoom.us/j/91608348235?pwd=ZVg4bEt2dWh2THI1WDBwY3 be AwQW1IUT09',
        zoomID: '916 0834 8235',
        zoomPW: 'sunrise',
        contactName: 'Gary'
    },
    {
        id: 15,
        visible: true,
        day: 'Tuesday',
        timePT: '8:15 AM PT',
        title: 'Wake Up and Smell the Coffee!',
        type: 'Al Anon',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://zoom.us/j/85759587914',
        zoomID: '857 5958 7914',
        zoomPW: '874152',
        contactName: 'Unknown'
    },
    {
        id: 16,
        visible: true,
        day: 'Tuesday',
        timePT: '9:00 AM PT',
        title: 'Breakfast Tacos',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/3893357431?pwd=ZnlYTm44QS9HVmxBTjJUZlRvb1Jydz09',
        zoomID: '389 335 7431',
        zoomPW: 'Sober2021',
        contactName: 'Aaron'
    },
    {
        id: 17,
        visible: true,
        day: 'Tuesday',
        timePT: '12:00 PM PT',
        title: 'Sober is Sexy: A Noon Meeting',
        type: 'AA',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/7667090526?pwd=MlVwbEFscU9CRmU1aFIyREcxZVV3UT09',
        zoomID: '766 709 0526',
        zoomPW: '019289',
        contactName: 'Alex & Hunter'
    },
    {
        id: 18,
        visible: true,
        day: 'Tuesday',
        timePT: '3:00 PM PT',
        title: 'Inside Issues: A Safe Place for the Dual Diagnosed Alcoholic',
        type: 'Dual Diagnosis',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/3893357431?pwd=ZnlYTm44QS9HVmxBTjJUZlRvb1Jydz09',
        zoomID: '389 335 7431',
        zoomPW: 'Sober2021',
        contactName: 'Tina'
    },
    {
        id: 19,
        visible: true,
        day: 'Tuesday',
        timePT: '5:00 PM PT',
        title: 'Happy, Joyous and Free in Sobriety',
        type: 'AA',
        format: 'Open',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown'
    },
    {
        id: 20,
        visible: true,
        day: 'Tuesday',
        timePT: '5:00 PM PT',
        title: 'Radford Women’s Back of the Book (c/w)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://zoom.us/j/112662426?pwd=NmlicVQvZ29qVTN5Q2VsQXNIUEJRQT09',
        zoomID: '112 662 426',
        zoomPW: '009932',
        contactName: 'Natara'
    },
    {
        id: 21,
        visible: true,
        day: 'Tuesday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Isidro C.'
    },
    {
        id: 22,
        visible: true,
        day: 'Tuesday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'Unknown'
    },
    {
        id: 23,
        visible: true,
        day: 'Tuesday',
        timePT: '7:00 PM PT',
        title: 'The 12 Steps',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'David H.'
    },
    {
        id: 24,
        visible: true,
        day: 'Tuesday',
        timePT: '7:30 PM PT',
        title: 'Straight Pepper Diet',
        type: 'SLAA/AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/81641504446?pwd=V3RybFZMUU9ycGY4WEtMWHdrVVhoUT09',
        zoomID: '816 4150 4446',
        zoomPW: 'Page69',
        contactName: 'Jesse T.'
    },
    {
        id: 25,
        visible: true,
        day: 'Tuesday',
        timePT: '9:00 PM PT',
        title: 'Wise Guys (Mens Stag)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Sevak'
    },
    {
        id: 26,
        visible: true,
        day: 'Tuesday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Andrea'
    },

    //WEDNESDAY
    {
        id: 27,
        visible: true,
        day: 'Wednesday',
        timePT: '7:00 AM PT',
        title: 'Back of the Book AA meeting',
        type: 'AA',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://zoom.us/j/91608348235?pwd=ZVg4bEt2dWh2THI1WDBwY3AwQW1IUT09',
        zoomID: '916 0834 8235',
        zoomPW: 'sunrise',
        contactName: 'Logan C.'
    },
    {
        id: 28,
        visible: true,
        day: 'Wednesday',
        timePT: '8:30 AM PT',
        title: 'In the Solution Alanon Meeting: For Family and Friends of Alcoholics',
        type: 'Al Anon',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://zoom.us/j/168127785',
        zoomID: '168127785',
        zoomPW: '375376',
        contactName: 'Cathy & Kristin'
    },
    {
        id: 29,
        visible: true,
        day: 'Wednesday',
        timePT: '9:00 AM PT',
        title: 'RAD CREATIVES in AA (Directors, producers, writers, actors, and all in creative fields)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Jacob'
    },
    {
        id: 30,
        visible: true,
        day: 'Wednesday',
        timePT: '11:00 AM PT',
        title: 'Gettin’ Lit: Weekly Book Study, Big Book Mondays, 12 Steps and 12 Traditions',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/82633330760?pwd=alpvUUdlbXhpaUZydWs5Z1Q0Zjlqdz09',
        zoomID: '826 3333 0760',
        zoomPW: 'Literature',
        contactName: 'Andi C.'
    },
    {
        id: 31,
        visible: true,
        day: 'Wednesday',
        timePT: '12:00 PM PT',
        title: 'ReLaPsE ScHmReLaPse',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Dr John & Andi C.'
    },
    {
        id: 32,
        visible: true,
        day: 'Wednesday',
        timePT: '3:00 PM PT',
        title: 'Act As If: Taking Contrary Action',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Ryan'
    },
    {
        id: 33,
        visible: true,
        day: 'Wednesday',
        timePT: '3:00 PM PT',
        title: 'Living the Design',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown'
    },
    {
        id: 34,
        visible: true,
        day: 'Wednesday',
        timePT: '4:30 PM PT',
        title: 'Intro To Nic-A for Smoking and Vaping Cessation',
        type: 'NicA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/7667090526?pwd=MlVwbEFscU9CRmU1aFIyREcxZVV3UT09',
        zoomID: '766 709 0526',
        zoomPW: '019289',
        contactName: 'Josh & Dr. John'
    },
    {
        id: 35,
        visible: true,
        day: 'Wednesday',
        timePT: '5:00 PM PT',
        title: 'unWINEd Wednesday',
        type: 'AA',
        format: 'Speaker',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/87577474505',
        zoomID: '875 7747 4505',
        zoomPW: 'N/A',
        contactName: 'Krystle & Kristen M.'
    },
    {
        id: 36,
        visible: true,
        day: 'Wednesday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Marion'
    },
    {
        id: 37,
        visible: true,
        day: 'Wednesday',
        timePT: '6:00 PM PT',
        title: 'Tens Only: A Tenth Step Meeting',
        type: 'AA',
        format: 'Unknown',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Marion'
    },
    {
        id: 38,
        visible: true,
        day: 'Wednesday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'N/A'
    },
    {
        id: 39,
        visible: true,
        day: 'Wednesday',
        timePT: '7:30 PM PT',
        title: 'Topic Lounge (Men’s Stag)',
        type: 'AA',
        format: 'Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown'
    },
    {
        id: 40,
        visible: true,
        day: 'Wednesday',
        timePT: '7:30 PM PT',
        title: 'Children of Chaos (12x12 study)',
        type: 'AA',
        format: 'Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown'
    },
    {
        id: 41,
        visible: true,
        day: 'Wednesday',
        timePT: '8:00 PM PT',
        title: 'RageRemedy (Anger and Resentment solutions)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/83657597076?pwd=RGZvRS9QZGdpTXNLQVJPQXd6ZFFZZz09',
        zoomID: '836 5759 7076',
        zoomPW: 'Healing',
        contactName: 'Maggie'
    },
    {
        id: 42,
        visible: true,
        day: 'Wednesday',
        timePT: '9:00 PM PT',
        title: 'WIP (Work In Progress) Men’s Stag',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/83707184774?pwd=RkVkVWVGTEdDN1puNGYzNC9FODBGQT09',
        zoomID: '837 0718 4774',
        zoomPW: '587953',
        contactName: 'Andy L',
        note: 'Live/Hybrid 1st Wednesday of the month (4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room), otherwise Online Only'
    },
    {
        id: 43,
        visible: true,
        day: 'Wednesday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Krystle'
    },

    //THURSDAY
    {
        id: 44,
        visible: true,
        day: 'Thursday',
        timePT: '8:15 AM PT',
        title: 'Wake Up and Smell The Coffee! (Alanon)',
        type: 'Al Anon',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/89331786908',
        zoomID: '893 3178 6908',
        zoomPW: 'N/A',
        contactName: 'Unknown'
    },
    {
        id: 45,
        visible: true,
        day: 'Thursday',
        timePT: '9:00 AM PT',
        title: 'Mom & Pop Shop: Parenting in Recovery',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/89389919893?pwd=Y09FMWRMU1ZFbzZSL2ZFRUJBdTV6Zz09',
        zoomID: '893 8991 9893',
        zoomPW: 'AAvillage',
        contactName: 'Erin'
    },
]
