export const meetings = [
    //MONDAY
    {
        id: 1,
        visible: true,
        day: 'Monday',
        timePT: '7:00 AM PT',
        title: 'Living Sober Sunrise Mtg: Reading from “Living Sober”',
        type: 'AA',
        format: 'Unknown',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://zoom.us/j/91608348235?pwd=ZVg4bEt2dWh2THI1WDBwY3AwQW1IUT09',
        zoomID: '916 0834 8235',
        zoomPW: 'sunrise',
        contactName: 'Crystal',
        note: ''
    },
    {
        id: 2,
        visible: true,
        day: 'Monday',
        timePT: '8:15 AM PT',
        title: 'Hope For Today (Al-Anon-ACA Focus)',
        type: 'ACA',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serentity Room',
        zoom: 'https://us02web.zoom.us/j/87887397285',
        zoomID: '878 8739 7285',
        zoomPW: '314887',
        contactName: '',
        note: ''
    },
    {
        id: 3,
        visible: true,
        day: 'Monday',
        timePT: '9:00 AM PT',
        title: 'The Stepper! A fun step study.',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Erik C.',
        note: ''
    },
    {
        id: 4,
        visible: true,
        day: 'Monday',
        timePT: '11:00 AM PT',
        title: 'Gettin’ Lit: Weekly Book Study, Big Book Mondays, 12 Steps, and 12 Traditions.',
        type: 'AA',
        format: 'Unknown',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/82633330760?pwd=alpvUUdlbXhpaUZydWs5Z1Q0Zjlqdz09',
        zoomID: '283 595 3698',
        zoomPW: 'Literature',
        contactName: 'Melissa H.',
        note: ''
    },
    {
        id: 5,
        visible: true,
        day: 'Monday',
        timePT: '12:00 PM PT',
        title: 'Parental Guidance: A meeting for sober parents in AA',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/89389919893?pwd=Y09FMWRMU1ZFbzZSL2ZFRUJBdTV6Zz09',
        zoomID: '893 8991 9893',
        zoomPW: 'AAvillage',
        contactName: 'Lauren',
        note: ''
    },
    {
        id: 6,
        visible: true,
        day: 'Monday',
        timePT: '1:30 PM PT',
        title: 'Zaddies & Addies: A safe space for LGBTQIA2S+ and allies to recover',
        type: 'AA',
        format: 'Literature/Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/3893357431?pwd=ZnlYTm44QS9HVmxBTjJUZlRvb1Jydz09',
        zoomID: '389 335 7431',
        zoomPW: 'Sober2021',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 7,
        visible: true,
        day: 'Monday',
        timePT: '3:00 PM PT',
        title: 'House of Cards: AA meeting focusing on the family dynamic in recovery',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/83585017311?pwd=eXJta3Q2eW9aTWwzZ3JaQlRiZ0NYUT09',
        zoomID: '835 8501 7311',
        zoomPW: '4343',
        contactName: 'Alyssa L.',
        note: ''
    },
    {
        id: 8,
        visible: true,
        day: 'Monday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Justin R.',
        note: ''
    },
    {
        id: 9,
        visible: true,
        day: 'Monday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'N/A',
        note: ''
    },
    {
        id: 10,
        visible: true,
        day: 'Monday',
        timePT: '7:00 PM PT',
        title: 'Double Trouble: A Safe Space to Discuss Dual Diagnosis',
        type: 'Dual Diagnoses',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/5013772720',
        zoomID: '501 377 2720',
        zoomPW: 'recovery',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 11,
        visible: true,
        day: 'Monday',
        timePT: '7:30 PM PT',
        title: 'Young Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Gabe',
        note: ''
    },
    {
        id: 12,
        visible: true,
        day: 'Monday',
        timePT: '8:00 PM PT',
        title: 'Humble Pride at Radford: LGBTQ AND SUPPORTERS!',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us04web.zoom.us/j/9072328568?pwd=bm5xZzdNOVE3ZEhKMHYwanVnVVl1dz09',
        zoomID: '907 232 8568',
        zoomPW: 'RPride',
        contactName: 'Gio',
        note: ''
    },
    {
        id: 13,
        visible: true,
        day: 'Monday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Ash',
        note: ''
    },

    //TUESDAY
    {
        id: 14,
        visible: true,
        day: 'Tuesday',
        timePT: '7:00 AM PT',
        title: 'First Things First: 12 x 12 Book Study',
        type: 'AA',
        format: 'Book Study',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us06web.zoom.us/j/91608348235?pwd=ZVg4bEt2dWh2THI1WDBwY3 be AwQW1IUT09',
        zoomID: '916 0834 8235',
        zoomPW: 'sunrise',
        contactName: 'Gary',
        note: ''
    },
    {
        id: 15,
        visible: true,
        day: 'Tuesday',
        timePT: '8:15 AM PT',
        title: 'Wake Up and Smell the Coffee!',
        type: 'Al-Anon',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://zoom.us/j/85759587914',
        zoomID: '857 5958 7914',
        zoomPW: '874152',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 16,
        visible: true,
        day: 'Tuesday',
        timePT: '9:00 AM PT',
        title: 'Breakfast Tacos',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/3893357431?pwd=ZnlYTm44QS9HVmxBTjJUZlRvb1Jydz09',
        zoomID: '389 335 7431',
        zoomPW: 'Sober2021',
        contactName: 'Aaron',
        note: ''
    },
    {
        id: 17,
        visible: true,
        day: 'Tuesday',
        timePT: '12:00 PM PT',
        title: 'Sober is Sexy: A Noon Meeting',
        type: 'AA',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/7667090526?pwd=MlVwbEFscU9CRmU1aFIyREcxZVV3UT09',
        zoomID: '766 709 0526',
        zoomPW: '019289',
        contactName: 'Alex & Hunter',
        note: ''
    },
    {
        id: 18,
        visible: true,
        day: 'Tuesday',
        timePT: '3:00 PM PT',
        title: 'Inside Issues: A Safe Place for the Dual Diagnosed Alcoholic',
        type: 'Dual Diagnosis',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/3893357431?pwd=ZnlYTm44QS9HVmxBTjJUZlRvb1Jydz09',
        zoomID: '389 335 7431',
        zoomPW: 'Sober2021',
        contactName: 'Tina',
        note: ''
    },
    {
        id: 19,
        visible: true,
        day: 'Tuesday',
        timePT: '5:00 PM PT',
        title: 'Happy, Joyous and Free in Sobriety',
        type: 'AA',
        format: 'Open',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 20,
        visible: true,
        day: 'Tuesday',
        timePT: '5:00 PM PT',
        title: 'Radford Women’s Back of the Book (c/w)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://zoom.us/j/112662426?pwd=NmlicVQvZ29qVTN5Q2VsQXNIUEJRQT09',
        zoomID: '112 662 426',
        zoomPW: '009932',
        contactName: 'Natara',
        note: ''
    },
    {
        id: 21,
        visible: true,
        day: 'Tuesday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Isidro C.',
        note: ''
    },
    {
        id: 22,
        visible: true,
        day: 'Tuesday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 23,
        visible: true,
        day: 'Tuesday',
        timePT: '7:00 PM PT',
        title: 'The 12 Steps',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'David H.',
        note: ''
    },
    {
        id: 24,
        visible: true,
        day: 'Tuesday',
        timePT: '7:30 PM PT',
        title: 'Straight Pepper Diet',
        type: 'SLAA/AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/81641504446?pwd=V3RybFZMUU9ycGY4WEtMWHdrVVhoUT09',
        zoomID: '816 4150 4446',
        zoomPW: 'Page69',
        contactName: 'Jesse T.',
        note: ''
    },
    {
        id: 25,
        visible: true,
        day: 'Tuesday',
        timePT: '9:00 PM PT',
        title: 'Wise Guys (Mens Stag)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Sevak',
        note: ''
    },
    {
        id: 26,
        visible: true,
        day: 'Tuesday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Andrea',
        note: ''
    },

    //WEDNESDAY
    {
        id: 27,
        visible: true,
        day: 'Wednesday',
        timePT: '7:00 AM PT',
        title: 'Back of the Book AA meeting',
        type: 'AA',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://zoom.us/j/91608348235?pwd=ZVg4bEt2dWh2THI1WDBwY3AwQW1IUT09',
        zoomID: '916 0834 8235',
        zoomPW: 'sunrise',
        contactName: 'Logan C.',
        note: ''
    },
    {
        id: 28,
        visible: true,
        day: 'Wednesday',
        timePT: '8:30 AM PT',
        title: 'In the Solution Al-Anon Meeting: For Family and Friends of Alcoholics',
        type: 'Al-Anon',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://zoom.us/j/168127785',
        zoomID: '168127785',
        zoomPW: '375376',
        contactName: 'Cathy & Kristin',
        note: ''
    },
    {
        id: 29,
        visible: true,
        day: 'Wednesday',
        timePT: '9:00 AM PT',
        title: 'RAD CREATIVES in AA (Directors, producers, writers, actors, and all in creative fields)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Jacob',
        note: ''
    },
    {
        id: 30,
        visible: true,
        day: 'Wednesday',
        timePT: '11:00 AM PT',
        title: 'Gettin’ Lit: Weekly Book Study, Big Book Mondays, 12 Steps and 12 Traditions',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/82633330760?pwd=alpvUUdlbXhpaUZydWs5Z1Q0Zjlqdz09',
        zoomID: '826 3333 0760',
        zoomPW: 'Literature',
        contactName: 'Andi C.',
        note: ''
    },
    {
        id: 31,
        visible: true,
        day: 'Wednesday',
        timePT: '12:00 PM PT',
        title: 'ReLaPsE ScHmReLaPse',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Dr John & Andi C.',
        note: ''
    },
    {
        id: 32,
        visible: true,
        day: 'Wednesday',
        timePT: '3:00 PM PT',
        title: 'Act As If: Taking Contrary Action',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Ryan',
        note: ''
    },
    {
        id: 33,
        visible: true,
        day: 'Wednesday',
        timePT: '3:00 PM PT',
        title: 'Living the Design',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 34,
        visible: true,
        day: 'Wednesday',
        timePT: '4:30 PM PT',
        title: 'Intro To Nic-A for Smoking and Vaping Cessation',
        type: 'NicA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/7667090526?pwd=MlVwbEFscU9CRmU1aFIyREcxZVV3UT09',
        zoomID: '766 709 0526',
        zoomPW: '019289',
        contactName: 'Josh & Dr. John',
        note: ''
    },
    {
        id: 35,
        visible: true,
        day: 'Wednesday',
        timePT: '5:00 PM PT',
        title: 'unWINEd Wednesday',
        type: 'AA',
        format: 'Speaker',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/87577474505',
        zoomID: '875 7747 4505',
        zoomPW: 'N/A',
        contactName: 'Krystle & Kristen M.',
        note: ''
    },
    {
        id: 36,
        visible: true,
        day: 'Wednesday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Marion',
        note: ''
    },
    {
        id: 37,
        visible: true,
        day: 'Wednesday',
        timePT: '6:00 PM PT',
        title: 'Tens Only: A Tenth Step Meeting',
        type: 'AA',
        format: 'Unknown',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Marion',
        note: ''
    },
    {
        id: 38,
        visible: true,
        day: 'Wednesday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'N/A',
        note: ''
    },
    {
        id: 39,
        visible: true,
        day: 'Wednesday',
        timePT: '7:30 PM PT',
        title: 'Topic Lounge (Men’s Stag)',
        type: 'AA',
        format: 'Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 40,
        visible: true,
        day: 'Wednesday',
        timePT: '7:30 PM PT',
        title: 'Children of Chaos (12x12 study)',
        type: 'AA',
        format: 'Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 41,
        visible: true,
        day: 'Wednesday',
        timePT: '8:00 PM PT',
        title: 'RageRemedy (Anger and Resentment solutions)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/83657597076?pwd=RGZvRS9QZGdpTXNLQVJPQXd6ZFFZZz09',
        zoomID: '836 5759 7076',
        zoomPW: 'Healing',
        contactName: 'Maggie'
    },
    {
        id: 42,
        visible: true,
        day: 'Wednesday',
        timePT: '9:00 PM PT',
        title: 'WIP (Work In Progress) Men’s Stag',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/83707184774?pwd=RkVkVWVGTEdDN1puNGYzNC9FODBGQT09',
        zoomID: '837 0718 4774',
        zoomPW: '587953',
        contactName: 'Andy L',
        note: 'Live/Hybrid 1st Wednesday of the month (4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room), otherwise Online Only'
    },
    {
        id: 43,
        visible: true,
        day: 'Wednesday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Krystle',
        note: ''
    },

    //THURSDAY
    {
        id: 44,
        visible: true,
        day: 'Thursday',
        timePT: '8:15 AM PT',
        title: 'Wake Up and Smell The Coffee! (Al-Anon)',
        type: 'Al-Anon',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/89331786908',
        zoomID: '893 3178 6908',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 45,
        visible: true,
        day: 'Thursday',
        timePT: '9:00 AM PT',
        title: 'Mom & Pop Shop: Parenting in Recovery',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/89389919893?pwd=Y09FMWRMU1ZFbzZSL2ZFRUJBdTV6Zz09',
        zoomID: '893 8991 9893',
        zoomPW: 'AAvillage',
        contactName: 'Erin',
        note: ''
    },
    {
        id: 46,
        visible: true,
        day: 'Thursday',
        timePT: '12:00 PM PT',
        title: 'The Rad Pack Men’s Stag',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/5020147373?pwd=T2tJZnNMSUF0N1BnLzdEem15UnNadz09',
        zoomID: '502 014 7373',
        zoomPW: 'moorpark3',
        contactName: 'Joe W.',
        note: ''
    },
    {
        id: 47,
        visible: true,
        day: 'Thursday',
        timePT: '12:00 PM PT',
        title: 'All the Sober Ladies: Lunch with us at Noon',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/7667090526?pwd=MlVwbEFscU9CRmU1aFIyREcxZVV3UT09',
        zoomID: '019289',
        zoomPW: 'N/A',
        contactName: 'Brianna',
        note: ''
    },
    {
        id: 48,
        visible: true,
        day: 'Thursday',
        timePT: '12:00 PM PT',
        title: 'Zombies by Day',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/89389919893?pwd=Y09FMWRMU1ZFbzZSL2ZFRUJBdTV6Zz09',
        zoomID: '893 8991 9893',
        zoomPW: 'AAvillage',
        contactName: 'Arthur',
        note: 'Thursday and Friday'
    },
    {
        id: 49,
        visible: true,
        day: 'Thursday',
        timePT: '1:30 PM PT',
        title: 'Zaddies and Addies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/3893357431?pwd=ZnlYTm44QS9HVmxBTjJUZlRvb1Jydz09',
        zoomID: '389 335 7431',
        zoomPW: 'Sober2021',
        contactName: 'Mikie C. & Julie',
        note: ''
    },
    {
        id: 50,
        visible: true,
        day: 'Thursday',
        timePT: '3:00 PM PT',
        title: 'Letting Go of The Bull****',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/83802795761?pwd=OFJURjQ0ejJZK0hRaXF5TVBnTm1EZz09',
        zoomID: '83802795761',
        zoomPW: 'letgo',
        contactName: 'Tiffany',
        note: ''
    },
    {
        id: 51,
        visible: true,
        day: 'Thursday',
        timePT: '4:30 PM PT',
        title: 'Radford Hall’s Thirsty Thursdays',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us05web.zoom.us/j/83056485054?pwd=TjZYeVd1Y1NaNzJEdUZhdUIyRmZ2Zz09',
        zoomID: '830 5648 5054',
        zoomPW: '675244',
        contactName: 'Maurice',
        note: ''
    },
    {
        id: 52,
        visible: true,
        day: 'Thursday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Paul V',
        note: ''
    },
    {
        id: 53,
        visible: true,
        day: 'Thursday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'N/A',
        note: ''
    },
    {
        id: 54,
        visible: true,
        day: 'Thursday',
        timePT: '7:00 PM PT',
        title: '“Secrets” AA Meeting',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us04web.zoom.us/j/75776835114?pwd=UHYyYU5ySjRJMGxrSUNtQ2lROGladz09',
        zoomID: '757 7683 5114',
        zoomPW: 'Secrets',
        contactName: 'Natasha',
        note: ''
    },
    {
        id: 55,
        visible: true,
        day: 'Thursday',
        timePT: '7:30 PM PT',
        title: 'Principles Before Personalities BBS',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/87205281971?pwd=TXZ2MFBveXlHUnMyT2oyQ090YjUzZz09',
        zoomID: '872 0528 1971',
        zoomPW: 'PBPBBS',
        contactName: 'Quincy',
        note: ''
    },
    {
        id: 56,
        visible: true,
        day: 'Thursday',
        timePT: '8:00 PM PT',
        title: 'The Love Boat: How to Relation-Ship',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/7667090526?pwd=MlVwbEFscU9CRmU1aFIyREcxZVV3UT09',
        zoomID: '766 709 0526',
        zoomPW: '019289',
        contactName: 'Melinda & Tawnee',
        note: ''
    },
    {
        id: 57,
        visible: true,
        day: 'Thursday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'France',
        note: ''
    },

    //FRIDAY
    {
        id: 58,
        visible: true,
        day: 'Friday',
        timePT: '8:15 AM PT',
        title: '4th Step Study (Alanon)',
        type: 'Al-Anon',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://zoom.us/j/83533107299',
        zoomID: '835 3310 7299',
        zoomPW: 'inventory',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 59,
        visible: true,
        day: 'Friday',
        timePT: '9:00 AM PT',
        title: 'Rise and Reflect',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/81504162089?pwd=czY3NlN2R1BNWmJtYUJGT3BRUmloQT09',
        zoomID: '815 0416 2089',
        zoomPW: 'Reflect',
        contactName: 'Paul',
        note: ''
    },
    {
        id: 60,
        visible: true,
        day: 'Friday',
        timePT: '11:00 AM PT',
        title: 'What Would Bill Do (WWBD)?',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/82633330760?pwd=alpvUUdlbXhpaUZydWs5Z1Q0Zjlqdz09',
        zoomID: '826 3333 0760',
        zoomPW: 'Literature',
        contactName: 'Logan C.',
        note: 'Reading and discussion from As Bill Sees It'
    },
    {
        id: 61,
        visible: true,
        day: 'Friday',
        timePT: '12:00 PM PT',
        title: 'Aloha Friday Step Study',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/82949212314?pwd=aGhnYzZHWm5Xem5samIrd2VQa2o2QT09',
        zoomID: '829 4921 2314',
        zoomPW: 'aloha',
        contactName: 'Brendan',
        note: '\'The Pacific Connection\''
    },
    {
        id: 62,
        visible: true,
        day: 'Friday',
        timePT: '12:00 PM PT',
        title: 'Zombies by Day',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/89389919893?pwd=Y09FMWRMU1ZFbzZSL2ZFRUJBdTV6Zz09',
        zoomID: '893 8991 9893',
        zoomPW: 'AAvillage',
        contactName: 'Michaela, Mel, & France',
        note: 'Thursday and Friday'
    },
    {
        id: 63,
        visible: true,
        day: 'Friday',
        timePT: '3:00 PM PT',
        title: 'AABUNDANCE (An AA Mtg Focused on Abundance)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us05web.zoom.us/j/83056485054?pwd=TjZYeVd1Y1NaNzJEdUZhdUIyRmZ2Zz09',
        zoomID: '830 5648 5054',
        zoomPW: '675244',
        contactName: 'Vikki from Manchester and Heather L.',
        note: ''
    },
    {
        id: 64,
        visible: true,
        day: 'Friday',
        timePT: '5:15 PM PT',
        title: 'MA Radford High Hopes',
        type: 'MA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/86040064528?pwd=WHFFYm14bVB1RnJpMjBQc1VDSkx6UT09',
        zoomID: '860 4006 4528',
        zoomPW: 'hope2all!',
        contactName: 'Jonathan C.',
        note: ''
    },
    {
        id: 65,
        visible: true,
        day: 'Friday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Little Patrick',
        note: ''
    },
    {
        id: 66,
        visible: true,
        day: 'Friday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'N/A',
        note: ''
    },
    {
        id: 67,
        visible: true,
        day: 'Friday',
        timePT: '6:45 PM PT',
        title: 'Women’s Step and Tradition Study',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/71150328609?pwd=WUlQN0tVa2NLRHpGU1ZEQjhoWkUrZz09',
        zoomID: '711 5032 8609',
        zoomPW: '16450',
        contactName: 'Dani',
        note: ''
    },
    {
        id: 68,
        visible: true,
        day: 'Friday',
        timePT: '8:00 PM PT',
        title: 'Freaky Friday: AA Meeting Where It is safe to talk About It All!',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Momo',
        note: ''
    },
    {
        id: 69,
        visible: true,
        day: 'Friday',
        timePT: '8:00 PM PT',
        title: 'Freaky Friday: AA Meeting Where It is safe to talk About It All!',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Momo',
        note: ''
    },
    {
        id: 70,
        visible: true,
        day: 'Friday',
        timePT: '9:00 PM PT',
        title: 'The Closer',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Jeff D. & Stephanie',
        note: 'Open to all'
    },
    {
        id: 71,
        visible: true,
        day: 'Friday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Melinda',
        note: ''
    },

    //SATURDAY
    {
        id: 72,
        visible: true,
        day: 'Saturday',
        timePT: '7:30 AM PT',
        title: 'Serenity Saturday - OA',
        type: 'OA',
        format: 'Speaker',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Reva',
        note: ''
    },
    {
        id: 73,
        visible: true,
        day: 'Saturday',
        timePT: '9:00 AM PT',
        title: 'Double Winners Meeting',
        type: 'AA',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us06web.zoom.us/j/85624927000?pwd=Vi83c1BoWmtKOTUxVVdXQWNHd083Zz09',
        zoomID: '856 2492 7000',
        zoomPW: 'keepsimple',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 74,
        visible: true,
        day: 'Saturday',
        timePT: '9:00 AM PT',
        title: 'Get the F*** Up!',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us06web.zoom.us/j/4209686309?pwd=dWkzNG1HZmJkeFV2cmlpRTVsdkIzQT09',
        zoomID: '420 968 6309',
        zoomPW: 'GTFU9',
        contactName: 'Wes',
        note: ''
    },
    {
        id: 75,
        visible: true,
        day: 'Saturday',
        timePT: '10:30 AM PT',
        title: 'Saturday Morning Alanon Live and Let Live',
        type: 'Al-Anon',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us06web.zoom.us/j/7246589151',
        zoomID: '724 658 9151',
        zoomPW: 'alanon',
        contactName: 'Lynnanne',
        note: ''
    },
    {
        id: 76,
        visible: true,
        day: 'Saturday',
        timePT: '10:30 AM PT',
        title: 'Up and Running: CEA HOW Womens Stag Meeting',
        type: 'CEA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us06web.zoom.us/j/550805512',
        zoomID: '550 805 512',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: 'No Passcode'
    },
    {
        id: 77,
        visible: true,
        day: 'Saturday',
        timePT: '11:00 AM PT',
        title: 'Let Go and Let Yoga',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/86415963987',
        zoomID: '864 1596 3987',
        zoomPW: 'N/A',
        contactName: 'Dave K.',
        note: 'Yoga / No Passcode'
    },
    {
        id: 78,
        visible: true,
        day: 'Saturday',
        timePT: '12:00 PM PT',
        title: 'From the Bar to The Book',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/5444957207?pwd=Zlk1UkNPSTd3akNwQW5LYWtBS09yUT09',
        zoomID: '544 495 7207',
        zoomPW: 'bar2book',
        contactName: 'Annika',
        note: 'Speaker w/ Big Book Passage & Participation'
    },
    {
        id: 79,
        visible: true,
        day: 'Saturday',
        timePT: '12:00 PM PT',
        title: 'Core of the Onion',
        type: 'ACA',
        format: 'Unknown',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: 'An ACA meeting (Adult Children of alcoholics/Dysfunctional families)'
    },
    {
        id: 80,
        visible: true,
        day: 'Saturday',
        timePT: '2:00 PM PT',
        title: 'Overserved: An AA meeting for Vets and supporters',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/81210452785?pwd=VzdTeHVyUWR3aitnSU5JNGIwb1I1QT09',
        zoomID: ' 812 1045 2785',
        zoomPW: 'recovery',
        contactName: 'David F.',
        note: 'Meeting opens early for fellowship'
    },
    {
        id: 81,
        visible: true,
        day: 'Saturday',
        timePT: '3:00 PM PT',
        title: 'Double D\'s: A safe place to talk about Dual Diagnosis in sobriety (AA)',
        type: 'AA / Dual Diagnosis',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/85753258368?pwd=VFhJaHdkcEdiODI2clZ3QkJ1cjVjdz09',
        zoomID: '857 5325 8368',
        zoomPW: 'dbld',
        contactName: 'Bleu',
        note: ''
    },
    {
        id: 82,
        visible: true,
        day: 'Saturday',
        timePT: '4:00 PM PT',
        title: 'Secular Healing: A Chapter FOR The Agnostic',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/9116680204?pwd=VnBwQWI2UW8vRlRsVHFiNTJPbEJVUT09',
        zoomID: '911 668 0204',
        zoomPW: 'tolerance',
        contactName: 'Michael',
        note: ''
    },
    {
        id: 83,
        visible: true,
        day: 'Saturday',
        timePT: '4:00 PM PT',
        title: 'Good Grief (AA): A safe place to discuss grief and loss in sobriety (AA)',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/4027665625?pwd=cVNGUzE5NzNzSlRtVFN5NDJ3YW0rUT09',
        zoomID: '402 766 5625',
        zoomPW: 'Hope',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 84,
        visible: true,
        day: 'Saturday',
        timePT: '6:00 PM PT',
        title: 'The Fix',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Bill L.',
        note: ''
    },
    {
        id: 85,
        visible: true,
        day: 'Saturday',
        timePT: '6:00 PM PT',
        title: 'Into The Triad',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'N/A',
        note: ''
    },
    {
        id: 86,
        visible: true,
        day: 'Saturday',
        timePT: '7:30 PM PT',
        title: 'Solutions in Sobriety (LGBTQ)',
        type: 'AA',
        format: 'Speaker',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/79596253473?pwd=SWV0UVlyb0RiNStOb1c0TXhFeDBKdz09',
        zoomID: '795 9625 3473',
        zoomPW: 'Solution20',
        contactName: 'Unknown',
        note: 'Two-Speakers'
    },
    {
        id: 87,
        visible: true,
        day: 'Saturday',
        timePT: '8:00 PM PT',
        title: 'Live from Radford: It’s Saturday Night!',
        type: 'AA',
        format: 'Participatiopn',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/83802795761?pwd=OFJURjQ0ejJZK0hRaXF5TVBnTm1EZz09',
        zoomID: '838 0279 5761',
        zoomPW: 'letgo',
        contactName: 'Serena "SZA" D. & Daniel B.',
        note: ''
    },
    {
        id: 88,
        visible: true,
        day: 'Saturday',
        timePT: '8:00 PM PT',
        title: 'THE GET DOWN',
        type: 'AA',
        format: 'Speaker',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: 'An Epic Speaker Meeting'
    },
    {
        id: 89,
        visible: true,
        day: 'Saturday',
        timePT: '9:00 PM PT',
        title: 'The Young Zombies: A place for young people in recovery',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/3893357431?pwd=ZnlYTm44QS9HVmxBTjJUZlRvb1Jydz09',
        zoomID: '389 335 7431',
        zoomPW: 'Sober2021',
        contactName: 'Lisa',
        note: 'AA - ALL are welcome.'
    },
    {
        id: 90,
        visible: true,
        day: 'Saturday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Moosh',
        note: ''
    },

    //SUNDAY
    {
        id: 91,
        visible: true,
        day: 'Sunday',
        timePT: '8:00 AM PT',
        title: '11th Step Prayer & Meditation',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us06web.zoom.us/j/83198617086?pwd=dUhYSGRXMy9aazdRRG1oSUNQV1pnQT09',
        zoomID: '831 9861 7086',
        zoomPW: '11thstep',
        contactName: 'Dawn',
        note: ''
    },
    {
        id: 92,
        visible: true,
        day: 'Sunday',
        timePT: '9:00 AM PT',
        title: 'Sounds of Sobriety: 11th Step Sound Bath Meditation Meeting',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Ken M & JJ',
        note: '(Earbuds/Headphones Recommended for Zoomers)'
    },
    {
        id: 93,
        visible: true,
        day: 'Sunday',
        timePT: '9:30 AM PT',
        title: 'Vision For You',
        type: 'CEA',
        format: 'Unknown',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/87691828632',
        zoomID: '876 9182 8632',
        zoomPW: '1212',
        contactName: 'Julianne',
        note: 'Compulsive Eaters Anonymous'
    },
    {
        id: 94,
        visible: true,
        day: 'Sunday',
        timePT: '9:30 AM PT',
        title: 'Radford Hall - BDA In the Solution',
        type: 'BDA',
        format: 'Unknown',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/975027580?pwd=L3c5aVQwTlRJM2U2S2JJNEZDejFmQT09',
        zoomID: '975 027 580',
        zoomPW: 'N/A',
        contactName: 'Mark or Rose',
        note: ''
    },
    {
        id: 95,
        visible: true,
        day: 'Sunday',
        timePT: '11:00 AM PT',
        title: 'Sister to Sister: An Inclusive Women\'s AA Book Study',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://zoom.us/j/81353172653',
        zoomID: '813 5317 2653',
        zoomPW: 'sis2sis',
        contactName: 'Maya',
        note: ''
    },
    {
        id: 96,
        visible: true,
        day: 'Sunday',
        timePT: '12:00 PM PT',
        title: 'Let the healing begin! 9th step and Promises Stories',
        type: 'AA',
        format: 'Unknown',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 97,
        visible: true,
        day: 'Sunday',
        timePT: '12:00 PM PT',
        title: 'I Like Big Books, and I Cannot Lie',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombiesl',
        contactName: 'Cass',
        note: ''
    },
    {
        id: 98,
        visible: true,
        day: 'Sunday',
        timePT: '3:00 PM PT',
        title: 'No Blame Game, Own That S***: An AA meeting to focus on our part',
        type: 'AA',
        format: 'Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/89754557391?pwd=bk5DVmpURngxUXBVMVJxcFlmbmgyZz09',
        zoomID: '897 5455 7391',
        zoomPW: 'forgive',
        contactName: 'Tawnee & LJ',
        note: ''
    },
    {
        id: 99,
        visible: true,
        day: 'Sunday',
        timePT: '5:00 PM PT',
        title: 'The Upside',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us02web.zoom.us/j/7667090526?pwd=MlVwbEFscU9CRmU1aFIyREcxZVV3UT09',
        zoomID: '766 709 0526',
        zoomPW: '019289',
        contactName: 'Amanda',
        note: ''
    },
    {
        id: 100,
        visible: true,
        day: 'Sunday',
        timePT: '6:00 PM PT',
        title: 'Radford Women\'s Topic-Participation',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/84214715979?pwd=TDNWeGViNjNNdjJ5VFZzaVpBZVhEQT09',
        zoomID: '842 1471 5979',
        zoomPW: '541338',
        contactName: 'Natara',
        note: 'Closed Meeting'
    },
    {
        id: 101,
        visible: true,
        day: 'Sunday',
        timePT: '6:00 PM PT',
        title: '4th Dimension',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'In Person',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'N/A',
        zoomID: 'N/A',
        zoomPW: 'N/A',
        contactName: 'Kory',
        note: ''
    },
    {
        id: 102,
        visible: true,
        day: 'Sunday',
        timePT: '6:00 PM PT',
        title: 'Into the Triad Beginners Meeting',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us06web.zoom.us/j/9959012824?pwd=ZUo0anJ4VEhFd0ZHdG1wNCticER2UT09',
        zoomID: '995 901 2824',
        zoomPW: '139431',
        contactName: 'N/A',
        note: ''
    },
    {
        id: 103,
        visible: true,
        day: 'Sunday',
        timePT: '7:00 PM PT',
        title: 'Open Up! Open Mic Performers AA Meeting',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us05web.zoom.us/j/8583733786?pwd=Y0Qvei9hUkNYTFhjNkdOalJ5UkhQdz09',
        zoomID: '858 373 3786',
        zoomPW: 'musicmeow',
        contactName: 'Sean P.',
        note: 'Expanding our comfort zones, even if you’ve never performed before. Five-minute shares can be Music, Poetry, Comedy, Karaoke, etc.'
    },
    {
        id: 104,
        visible: true,
        day: 'Sunday',
        timePT: '7:30 PM PT',
        title: 'Radford Pillbillies',
        type: 'PA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Serenity Room',
        zoom: 'https://us02web.zoom.us/j/84722690404?pwd=ZkM3UFNjQUl0eXZQdjRPSjlndUkvQT09',
        zoomID: '847 2269 0404',
        zoomPW: 'pillz',
        contactName: 'Tiffany',
        note: ''
    },
    {
        id: 105,
        visible: true,
        day: 'Sunday',
        timePT: '8:45 PM PT',
        title: 'Rad Women (Women’s Stag)',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/5013772720',
        zoomID: '501 377 2720',
        zoomPW: 'recovery',
        contactName: 'Nic',
        note: ''
    },
    {
        id: 106,
        visible: true,
        day: 'Sunday',
        timePT: '8:30 PM PT',
        title: 'Secular Healing: A Chapter FOR The Agnostic',
        type: 'AA',
        format: 'Participation',
        method: 'Online',
        physicalLocation: 'N/A',
        zoom: 'https://us02web.zoom.us/j/9116680204?pwd=VnBwQWI2UW8vRlRsVHFiNTJPbEJVUT09',
        zoomID: '911 668 0204',
        zoomPW: 'tolerance',
        contactName: 'Unknown',
        note: ''
    },
    {
        id: 13,
        visible: true,
        day: 'Sunday',
        timePT: '10:00 PM PT',
        title: 'Radford Zombies',
        type: 'AA',
        format: 'Speaker/Participation',
        method: 'Hybrid',
        physicalLocation: '4849 Van Nuys Blvd suite 103 Sherman Oaks - Radford Room',
        zoom: 'https://us04web.zoom.us/j/2835953698?pwd=V1NDdXU0OUFJcjUxZjVoWENKMStRZz09',
        zoomID: '283 595 3698',
        zoomPW: 'Zombies',
        contactName: 'Emily',
        note: ''
    },
]
